### ISSUE TITLE
Want a feedback

### ISSUE THREAD

**Issue by stiebrs** [TheMarkster/RADAR#1]
Hi,
I accidentally bumped into this project. I'm not very familiar with GitHub, so didn't know any other way of contacting you. 
This project generally seems to be a re-implementation of 2011 MIT 2.4GHz DIY radar. General question before printing, assembling and testing the board - did it work? If not, which parts need reworking/improvements? It looks like you have taken SKY67107 LNA eval board schematic as a basis but have changed some values on your schematic. Why's that? Just component availability or actual tweaking for performance?

It seems that I've generally followed the same design, approach and even components (found this repo based on search for SkyWorks LNA :)

Thanks

**Comment by TheMarkster** [comment]
Hi,

This was actually a prototype that I did quickly so it was a little rough. Long story short, the board did not work, but this is not the final version. 

The design was originally done on 62mil FR4, which was one of the main issues: the coupler was difficult to implement, 50ohm lines were huge compared to the devices, and many of the reference designs were done on a different substrate. I didn't have the time or lab resources to design my own matching circuits so I had to do a best guess on the design using the reference designs. Component values differed because the application note was in a different band or I was attempting to compensate for the aforementioned substrate differences. 

When the board was tested, the PA was not working as intended. I could see the LO at the RF output with the PA disabled, but when it was biased, we were not seeing the LO being properly amplified. I believe the PA was unstable in addition to the tuning being off. Since the PA was not functioning, we also weren't able to pass the LO to the mixer making further testing very difficult. 

I have a later version that is done on 8mil FR4 that is much cleaner. At this time it is not posted. I will try to let you know in the future if I choose to release it.

Thanks,
Mark

**Comment by stiebrs** [comment]
Hi,
Thanks for the response, saves me the trouble of debugging the whole thing. Since you have improved your design, I'll leave it be in hopes that you eventually do decide to publish. Designing from scratch is more fun anyway, and that's what I'm gonna do... eventually :)
